In [12]:
import pandas as pd

In [13]:
dataset = pd.read_excel(r'D:\HOPE AI\2. AI Course\Week 3. MACHINE LEARNING REGRESSION\1. Simple Linear Regression\Salary_Data.xlsx')

In [14]:
dataset

    S.No  Years Experience  Salary
0      1               1.0    2500
1      2               1.5    2700
2      3               2.0    2950
3      4               2.5    3150
4      5               3.0    3300
5      6               3.5    3500
6      7               4.0    3650
7      8               4.5    3850
8      9               5.0    4000
9     10               5.5    4200
10    11               6.0    4350
11    12               6.5    4550
12    13               7.0    4700
13    14               7.5    4900
14    15               8.0    5050
15    16               8.5    5250
16    17               9.0    5400
17    18               9.5    5600
18    19              10.0    5750
19    20              10.5    5950
20    21              11.0    6100
21    22              11.5    6300
22    23              12.0    6450
23    24              12.5    6650
24    25              13.0    6800
25    26              13.5    7000
26    27              14.0    7150
27    28              14.5    7300
28    29              15.0    7450
29    29              15.5    7600
30    29              16.0    7750

In [18]:
independent=dataset[["Years Experience"]]
independent

    Years Experience
0                1.0
1                1.5
2                2.0
3                2.5
4                3.0
5                3.5
6                4.0
7                4.5
8                5.0
9                5.5
10               6.0
11               6.5
12               7.0
13               7.5
14               8.0
15               8.5
16               9.0
17               9.5
18              10.0
19              10.5
20              11.0
21              11.5
22              12.0
23              12.5
24              13.0
25              13.5
26              14.0
27              14.5
28              15.0
29              15.5
30              16.0

In [19]:
dependent=dataset[["Salary"]]

In [23]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(independent, dependent, test_size=0.30,random_state=0)

In [26]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train,Y_train)

LinearRegression()

In [30]:
weight=regressor.coef_
weight

array([[349.45217987]])

In [31]:
bais=regressor.intercept_
bais

array([2247.13535722])

In [34]:
y_pred=regressor.predict(X_test)

In [38]:
from sklearn.metrics import r2_score
r_score=r2_score(Y_test,y_pred)

In [39]:
r_score

0.9995188138014284

In [40]:
import pickle
filename="finalized_model_linear.sav"

In [41]:
pickle.dump(regressor,open(filename,'wb'))

In [43]:
loaded_model=pickle.load(open("finalized_model_linear.sav",'rb'))
result=loaded_model.predict([[10]])

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [44]:
result

array([[5741.6571559]])