In [1]:
	# Before go into the model 3 things need to do Domain selection 
	# 1. Machine Learning - I/P and O/P  (Simple Linear Regression)
	# 2. Based on user  I/P and O/P it is- Supervised learning 
    # 3. (Classification/Regression ) Based on Numerical value O/P it is Regression 
	# Follow as per the MAPPING STEP BY STEP same steps for all the model.
	
	# Import pandas library (used to handle datasets like Excel (or) CSV-Comma Separated Value) there are 1000 of formula in pandas already loaded we just use it for our job.
	
	# as used for pands as pd short form
import pandas as pd

In [5]:
	# Open the Anaconda Navigator file and open Jupyter notebook and open the new folder for this M/L and use it and give proper naming as well as.
	# Read CSV file and store it in 'dataset'
dataset = pd.read_csv(r'D:\HOPE AI\2. AI Course\Week 3. MACHINE LEARNING REGRESSION\1. Simple Linear Regression\Salary_Data.csv')

In [6]:
	# Display the dataset (table view) check the file weather it is loaded correct or not always make sure before go to next set check and go 
dataset

    S.No  Years Experience  Salary
0      1               1.0    2500
1      2               1.5    2700
2      3               2.0    2950
3      4               2.5    3150
4      5               3.0    3300
5      6               3.5    3500
6      7               4.0    3650
7      8               4.5    3850
8      9               5.0    4000
9     10               5.5    4200
10    11               6.0    4350
11    12               6.5    4550
12    13               7.0    4700
13    14               7.5    4900
14    15               8.0    5050
15    16               8.5    5250
16    17               9.0    5400
17    18               9.5    5600
18    19              10.0    5750
19    20              10.5    5950
20    21              11.0    6100
21    22              11.5    6300
22    23              12.0    6450
23    24              12.5    6650
24    25              13.0    6800
25    26              13.5    7000
26    27              14.0    7150
27    28              14.5    7300
28    29              15.0    7450
29    29              15.5    7600
30    29              16.0    7750

In [12]:
	# Select independent variable (it is a input variable or feature) 
	# Here: In this case we use Years Experience → HR want to use to predict salary from the csv file input 
    # check it weather it is properly load or not
#need to start from the first if not found indefication error
independent = dataset[["Years Experience"]]
independent

    Years Experience
0                1.0
1                1.5
2                2.0
3                2.5
4                3.0
5                3.5
6                4.0
7                4.5
8                5.0
9                5.5
10               6.0
11               6.5
12               7.0
13               7.5
14               8.0
15               8.5
16               9.0
17               9.5
18              10.0
19              10.5
20              11.0
21              11.5
22              12.0
23              12.5
24              13.0
25              13.5
26              14.0
27              14.5
28              15.0
29              15.5
30              16.0

In [13]:
	# Select dependent variable - salary is the O/P  (target/output) 
	# Here: Salary → what we want to predict for different years of experience 
dependent = dataset[["Salary"]]

In [14]:
	# Import function to split dataset into 70% Training Set & 30% Testing Set 
    # By using the method sklearn is the MODEL - selection is the FUNCTION always use underscore for the line to consider as one line 
from sklearn.model_selection import train_test_split

In [16]:
	# Split data: divide the csv file into Train Set and Test Set
	# 70% for training, 30% for testing
	# random_state=0 ensures same split every time 
    # Below is the formula for need to use for all the model need to know 
X_train, X_test, Y_train, Y_test = train_test_split(independent, dependent, test_size=0.30, random_state=0)
    # Until here all the things same for ALL Algorithms

In [17]:
	# Hands on model creation learning PHASE -1 
	# Based on 1 I/p and 1 O/P we choose as SLR model 
	# Import Linear Regression model
	# This is the PROCEDURE we need to teach them correctly then only it will give good result and get high marks
from sklearn.linear_model import LinearRegression

In [18]:
	# Create model object for our work
    #  always write as it is
	# Learning phase 
regressor = LinearRegression()

In [19]:
	# Train the model using training data (Model EXAM)
regressor.fit(X_train, Y_train)

LinearRegression()

In [20]:
	# Our formula y=mX + C 
	# y = O/P (which forms a straight line by adding all data points)
	# mX = Slope - Weight (Which says about constant distance b/w 2 datapoints)
	# C = Bais - intercept - straight of the straight line (minimum value) 
	# Get slope (weight) → how much salary increases per year 
weight = regressor.coef_
weight

array([[349.45217987]])

In [21]:
	# Get intercept (bias) → base salary when experience = 0
bais = regressor.intercept_
bais

array([2247.13535722])

In [22]:
	# War B/W actual and predict value 
	# Predict salary for test data
y_pred = regressor.predict(X_test)

In [23]:
	# Import R² score function (model accuracy check)
from sklearn.metrics import r2_score

In [24]:
	# Calculate accuracy (0 is worst or near to 1 is GOOD model)
	# by using the r2 to know how well the model is fitted to our work
r_score = r2_score(Y_test, y_pred)

In [25]:
	# Display accuracy 
r_score

0.9995188138014284

In [26]:
    # value is 0.99951881 near to 1 so it is good model
	# So Save the trained model by using pickle function for further use 
import pickle

In [27]:
    # File name to save model as it do not change the name 
filename = "finalized_model_linear.sav"

In [28]:
	# Save model into file 
pickle.dump(regressor, open(filename, 'wb'))

In [36]:
	# Deployment = Phase - 2 
	# If you want to shows to customer below details is enough 
	# Load the saved model in pickle
loaded_model = pickle.load(open("finalized_model_linear.sav", 'rb'))

In [37]:
	# Predict salary for 10 years experience from user 
	# ([[ ]]) always use like this for I/P 
    # User input
experience = 10

In [38]:
    # Create DataFrame with same column name used in training
test_data = pd.DataFrame({"Years Experience": [experience]})

In [39]:
    # Predict
result = loaded_model.predict(test_data)

In [40]:
print("Predicted Salary =", result[0][0])

Predicted Salary = 5741.657155900479